# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6452062c06fcfd1e8cf3956a52a5ae95"
application_url = "https://innocent-harry-occurrence-them.trycloudflare.com"
embedded = true
name = "closed-hours-app"
handle = "closed-hours-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_metaobject_definitions, write_metaobjects, read_metaobject_definitions, read_metaobjects, read_orders"

[auth]
redirect_urls = [
  "https://innocent-harry-occurrence-them.trycloudflare.com/auth/callback",
  "https://innocent-harry-occurrence-them.trycloudflare.com/auth/shopify/callback",
  "https://innocent-harry-occurrence-them.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
